### ISSUE TITLE
access token auth with refresh token

### ISSUE THREAD

**Issue by D3PSI** [lumium-technologies/lumium#220]
we want to implement a more complete JWT auth scheme with a refresh token, to avoid hitting the DB on every request to verify whether the token is black flagged.

**Comment by D3PSI** [comment]
our current JWT implementation is perfectly secure, however it is not particularly fast as we hit the database every time when verifying whether the token has been blacklisted (which is the case after a user logs out. we then need to blacklist the long-lived access token as otherwise, if the token got stolen a malicious actor could authenticate with it until token expiration and we would not notice it). with a refresh token we lose a bit of security but we increase performance by not hitting the db every time on verification. will be a trade-off in the future

**Comment by cedricschwyter** [comment]
superseded by #266
