### ISSUE TITLE
introduce redux for state management

### ISSUE THREAD

**Issue by D3PSI** [lumium-technologies/lumium#98]
**Is your feature request related to a problem? Please describe.**
we want redux to manage the frontend state and state updates

**Describe the solution you'd like**
using redux we can more easily resolve #82 for example

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by theArgex** [comment]
I have a small suggestion. DON'T everyone hates the tech even the main maintainer recommends using anything else.


Good stuff though: https://www.npmjs.com/package/zustand 

But I'm sure there are a ton of other libs. We could technically just useSWR like we did in frontend-next

If you want I could take a look at #81 and this issue here.

**Comment by D3PSI** [comment]
@theArgex yeah, in any case we need to sit together and discuss about the frontend, afterall there is #140, and i personally don't really know how to maintain and scale a frontend codebase in a nice way. so now we're in a weird situation where some core functionality (like creating a new workspace and end to end encryption) works, but we have absolutely no frontend for this stuff. i've also wasted a lot of time on the frontend lately, so i have not been working on the API at all really, which means the API is also not very usable atm. but we'll get there and we know what we still need

**Comment by theArgex** [comment]
That's my specialty. But I guess you have to get some people on board.

**Comment by D3PSI** [comment]
well, we do have some people on board ready to help out in frontend, 
@reddixt and @edbingo can both help out there

**Comment by theArgex** [comment]
Awesome, thanks!

**Comment by D3PSI** [comment]
we can talk in the discord over the weekend/tomorrow, also with @reddixt 
maybe :+1

**Comment by D3PSI** [comment]
i am not sure if we really need this. there is no real use case for now. except maybe for #82. but i guess we can find a workaround for that. closing this for now, we can always come back to it later
